### ISSUE TITLE
About the release of the code

### ISSUE THREAD

**Issue by dgliu** [wujcan/GCM#1]
Hi, when is the source code expected to be released, or is it possible to obtain a copy in advance?

**Comment by wujcan** [comment]
> Hi, when is the source code expected to be released, or is it possible to obtain a copy in advance?

I will upload the code next month.

**Comment by dgliu** [comment]
> > Hi, when is the source code expected to be released, or is it possible to obtain a copy in advance?
> 
> I will upload the code next month.

Thank you for your reply, and look forward to your upload. In addition, can you also provide the process of generating item features and context features and the specific elements contained in the dataset statistics?

For example, for Amaon-book, the item features described in the paper include two attributes: price and brand, but the value in the table is 24,816. The context features include the year, month, day, day of week (i.e., day of the week?) and last purchase (i.e., is it the last item purchased by the user?), but the value in the table is 46,900. 

I simply count all possible values of prices and brands in the dataset, but it seems that I cannot get similar results.

**Comment by wujcan** [comment]
> > > Hi, when is the source code expected to be released, or is it possible to obtain a copy in advance?
> > 
> > 
> > I will upload the code next month.
> 
> Thank you for your reply, and look forward to your upload. In addition, can you also provide the process of generating item features and context features and the specific elements contained in the dataset statistics?
> 
> For example, for Amaon-book, the item features described in the paper include two attributes: price and brand, but the value in the table is 24,816. The context features include the year, month, day, day of week (i.e., day of the week?) and last purchase (i.e., is it the last item purchased by the user?), but the value in the table is 46,900.
> 
> I simply count all possible values of prices and brands in the dataset, but it seems that I cannot get similar results.

Actually, not every single value of the price is treated as a unique feature. I have divided the price into buckets.
