### ISSUE TITLE
Questions about data?

### ISSUE THREAD

**Issue by jinweiluo** [wujcan/GCM#2]
Hi, I encounter a problem when I try to analyze the data.

There are many "0" in the city's values in NC datasets and I am wondering if 0 is the padding of this context feature. 

In addition, I want to know how you deal with the missing context id in each sample in the data preprocessing.

**Comment by wujcan** [comment]
We simply discard those samples with missing context id, so value 0 is not the padding of context feature.

**Comment by jinweiluo** [comment]
Thanks!!!!
